export const COUNTRIES = [
    {id: 1,title : 'Afghanistan'},
    {id: 2,title : 'Bahrain'},
    {id: 3,title : 'Cambodia'},
    {id: 4,title : 'Denmark'},
    {id: 5,title : 'Ecuador'},
    {id: 6,title : 'Egypt'},
    {id: 7,title : 'Finland'},
    {id: 8,title : 'Guinea'},
    {id: 9,title : 'Iran'},
    {id: 10,title : 'Kenya'},
    {id: 11,title : 'Lebanon'},
    {id: 12,title : 'Mali'},
    {id: 13,title : 'Morocco'},
    {id: 14,title : 'Nigeria'},
    {id: 15,title : 'Russia'},
    {id: 16,title : 'Turkey'},
    {id: 17,title : 'Uruguay'},
    {id: 18,title : 'Vietnam'},
    {id: 19,title : 'Zambia'},
    {id: 20,title : 'Zimbabwe'}
]